Make it possible to disable commands dynamically
element-hq/mautrix-python pull request #1
Opened 2021-10-06 12:59 UTC by tadzik

This allows for hiding them completely depending on e.g. a config setting, or arbitrary sender rules (up to the implementing bridge).

Also accidentally upstreamed already to https://github.com/mautrix/python/pull/56 – no harm done (though I planned for it to pass here first), but we probably want this for ourselves regardless.

2021-10-06 13:05 UTC, jaller94 requested changes
Were is the configurable part?

I don't see how we could make this return False? (implying one cannot defined a lambda inside a config file.

2021-10-06 13:05 UTC, jaller94 commented on mautrix/bridge/commands/handler.py
> +                 is_enabled_for: IsEnabledForFunc = lambda _: True,
Shouldn't this be True or False? (implying this is the return type declaration of that lamda)

```suggestion
                 is_enabled_for: IsEnabledForFunc = lambda _: bool,
```

2021-10-06 13:06 UTC, tadzik commented on mautrix/bridge/commands/handler.py
> +                 is_enabled_for: IsEnabledForFunc = lambda _: True,
That's the default value, not the type signature. This makes the parameter optional, and backwards compatible.

2021-10-06 13:07 UTC, tadzik commented
> Were is the configurable part?
> 
> I don't see how we could make this return False? (implying one cannot defined a lambda inside a config file.

That is up to a bridge implementation. An example usecase is here: https://github.com/vector-im/mautrix-signal/pull/1

2021-10-06 13:47 UTC, tadzik commented on mautrix/bridge/commands/handler.py
>                  handler = command_aliases[command]
Good catch. Fixed it in 697e4e93049aa5df0c0e821f3294ec0fc68284a3, I think it made the code tidier as well.

2021-10-12 12:46 UTC, tadzik commented
This has been merged upstream now (including the suggestions from y'all) so we just need to pull that instead and save ourselves future merge conflicts.

2021-10-12 12:46 UTC, closed without merging